export const listWords = [
    "chat", "sable", "poisson", "maison", "avion", "rouge", "tableau", "plante", "étoile", "couteau",
    "terre", "chapeau", "pierre", "vache", "fleur", "cadeau", "travail", "orange", "soleil", "forêt",
    "brosse", "livre", "danse", "glace", "porte", "ciel", "voyage", "sourire", "fouet", "poème",
    "oiseau", "jouet", "classe", "manger", "histoire", "canard", "écrire", "bateau", "fruit", "pomme",
    "banane", "gâteau", "tarte", "légume", "poulet", "musique", "lumière", "école", "science", "espace",
    "crayon", "dictionnaire", "éléphant", "souris", "ordinateur", "chemin", "chanson", "temps", "montagne",
    "plage", "nuage", "fruits", "fleurs", "légumes", "oiseaux", "plantes", "champ", "route", "voiture",
    "livre", "histoire", "conte", "mystère", "étrange", "magie", "lune", "étoiles", "planète", "fusée",
    "couteau", "fourchette", "cuillère", "assiette", "verre", "table", "chaise", "fenêtre", "porte", "clé",
    "téléphone", "ordinateur", "musique", "chanson", "temps", "montagne", "plage", "bateau", "nuage", "fruits",
    "fleurs", "légumes", "oiseaux", "plantes", "champ", "route", "voiture", "livre", "histoire", "conte",
    "mystère", "étrange", "magie", "lune", "étoiles", "planète", "fusée", "couteau", "fourchette", "cuillère",
    "assiette", "verre", "table", "chaise", "fenêtre", "porte", "clé", "téléphone", "ordinateur", "musique",
    "chanson", "temps", "montagne", "plage", "bateau", "nuage", "fruits", "fleurs", "légumes", "oiseaux",
    "plantes", "champ", "route", "voiture", "livre", "histoire", "conte", "mystère", "étrange", "magie",
    "lune", "étoiles", "planète", "fusée", "couteau", "fourchette", "cuillère", "assiette", "verre", "table",
    "chaise", "fenêtre", "porte", "clé", "téléphone", "ordinateur", "musique", "chanson", "temps", "montagne",
    "plage", "bateau", "nuage", "fruits", "fleurs", "légumes", "oiseaux", "plantes", "champ", "route", "voiture"
];
